# Generated by Django 4.1.3 on 2023-02-09 00:18

from django.db import migrations, models
import djangojokes.storage_backends
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', upload_to='resumes', validators=[jobs.models.validate_pdf], verbose_name=djangojokes.storage_backends.PrivateMediaStorage()),
        ),
    ]
