# Generated by Django 4.1.3 on 2023-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_alter_category_category_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
