# Generated by Django 4.1.3 on 2023-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_jokevote_jokevote_one_vote_per_user_per_joke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jokes', to='jokes.tag'),
        ),
    ]
